### ISSUE TITLE
[Refactoring] Funciones en el SELECT

### ISSUE THREAD

**Issue by abalderas** [rubenperezm/Chatbot#2]
**Descripción**
Si el estudiante olvida una función en el SELECT, el sistema le dice que no ha seleccionado bien los campos, cuando en realidad el problema es que no ha elegido bien la función (o la ha olvidado). Pero la columna sí está bien elegida.

**Pasos para reproducir el error**
1. Consulta: Listado que muestre para cada nombre de artículo de los almacenados, su precio de coste y de venta medio con un redondeo de dos dígitos. Utiliza, respectivamente, los siguientes alias para estas dos últimas columnas: 'precio de coste medio' y 'precio de venta medio'
2. Respondo: select art_nom, round(avg(art_pc),2) 'precio de coste medio', avg(art_pv) 'precio de venta medio' from articulos group by art_nom;
3. Me he comido la función **round**. Sin embargo, el mensaje de consejo del chatbot dice que no he seleccionado los campos correctamente.

**Comment by rubenperezm** [comment]
Resuelto
