### ISSUE TITLE
[Refactoring] Consejos del chatbot cuando el estudiante renombra consultas

### ISSUE THREAD

**Issue by abalderas** [rubenperezm/Chatbot#3]
**Descripción**
Si el estudiante renombra un campo, el sistema le dice: "No debes renombrar los campos del select". Yo lo cambiaría por "No debes renombrar los campos del select si el enunciado no lo dice explícitamente"

Y cuando hay un error en el renombramiento, le diría que "El renombramiento debe coincidir literalmente con el especificado en el enunciado".

**Comment by rubenperezm** [comment]
Resuelto
