### ISSUE TITLE
[Improvement] Centrar mensajes de popup

### ISSUE THREAD

**Issue by juanantonioch84** [rubenperezm/Chatbot#6]
Colocar el mensaje del tutorial y el de Enhorabuena en el centro de la pantalla, ya que actualmente aparecen muy a la derecha:
![image](https://user-images.githubusercontent.com/36247675/160935001-4e334bdb-7975-4e60-899e-a6e6c7e6feba.png)

**Comment by rubenperezm** [comment]
Resuelto en 'BloqueSolucion Centrado y logs sin profesores'
![image](https://user-images.githubusercontent.com/80062165/160936346-5797ab47-562f-431f-88da-e3dabf42c114.png)
