### ISSUE TITLE
[Improvement] Mejorar la visibilidad de la relación entre tablas

### ISSUE THREAD

**Issue by juanantonioch84** [rubenperezm/Chatbot#8]
Poder ver más claramente cómo se relacionan las tablas (al menos, los campos que actúan como FK). El desarrollador propone la solución siguiente: se podría añadir esa pregunta al chatbot y que éste responda con las relaciones entre las tablas (por ejemplo, con una imagen mostrando el esquema de la base de datos).

**Comment by rubenperezm** [comment]
Se ha cambiado el diálogo del chatbot para que cuando se pregunte por la estructura de la base de datos responda de la siguiente manera:
![image](https://user-images.githubusercontent.com/80062165/160937730-7547d9c8-93d1-47e7-9b36-c4e07fa66721.png)

La imagen es ampliable, para poder verla con mayor facilidad. Se puede invocar esta respuesta con mensajes como:
"qué relaciones existen en la base de datos"
"cuál es la estructura de la base de datos"
"muéstrame el esquema con las tablas"
